class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tetsukyojins 
  has_many :red_uruhuramaiters
  has_many :blue_uruhuramaiters
  has_many :dualhorns
  has_many :gurendels
  has_many :pyurobols
  has_many :varahs
  has_many :bombs
  has_many :grenades
  has_many :fungongos
  has_many :sorns
  has_many :antesantans
  has_many :vivres
  has_many :ramashtus
  has_many :ksarliks
  has_many :mushufshes
  has_many :needsheggs
  has_many :lalds
  has_many :vanips
  has_many :murhushes
  has_many :mahouts
  has_many :shreds
  has_many :harmas
  has_many :yellows
  has_many :whites
  has_many :reds
  has_many :golds
  has_many :blues
  has_many :darks
  has_many :blacks
  has_many :waters
  has_many :thunders
  has_many :snows
  has_many :flames
  has_many :ices
  has_many :darkps
  has_many :floateyes
  has_many :buells
  has_many :evileyes
  has_many :ahrimans
  has_many :deathfloats
  has_many :gandharvas
  has_many :airloges
  has_many :gulquimaseras
  has_many :killerbees
  has_many :bytebugs
  has_many :wasps
  has_many :neviros
  has_many :condors
  has_many :seamulgs
  has_many :arcuones
  has_many :dinonics
  has_many :ipils
  has_many :rapturs
  has_many :merusines
  has_many :schmerkes
  has_many :yowees
  has_many :zauras
  has_many :dingos
  has_many :michenfangs
  has_many :garms
  has_many :snowwolves
  has_many :sandwolves
  has_many :skols
  has_many :bandersnatches
  has_many :balsams
  has_many :galdas
  has_many :basilisks
  has_many :ochus
  has_many :unsabotenders
  has_many :larvas
  has_many :kushipos
  has_many :chimeras
  has_many :zoos
  has_many :sandworms
  has_many :sabotenders
  has_many :quals
  has_many :hedgevipers
  has_many :ogres
  has_many :morbols
  has_many :chimerabrains
  has_many :epages
  has_many :ghosts
  has_many :domperis
  has_many :glatts
  has_many :mandragoras
  has_many :behemoths
  has_many :splashers
  has_many :akeolos
  has_many :ragings
  has_many :ashuras
  has_many :wraiths
  has_many :devilmonoliths
  has_many :morbolgreats
  has_many :barbados
  has_many :adamantais
  has_many :kingbehemoths
  has_many :spirits
  has_many :metiers
  has_many :masterquals
  has_many :masterdomperis
  has_many :varnas
end
